package bista.shiddarth.dotacounterpicker.model

class HeroMap {
    companion object {
        val heroIdMap = mapOf(
            "Anti-mage" to 1,
            "anti-mage" to 1,
            "am" to 1,
            "antimage" to 1,
            "Axe" to 2,
            "axe" to 2,
            "Bane" to 3,
            "baneelemental" to 3,
            "bane" to 3,
            "atropos" to 3,
            "Bloodseeker" to 4,
            "bs" to 4,
            "bloodseeker" to 4,
            "Crystal Maiden" to 5,
            "cm" to 5,
            "crystalmaiden" to 5,
            "Drow Ranger" to 6,
            "drow" to 6,
            "drowranger" to 6,
            "Earthshaker" to 7,
            "earthshaker" to 7,
            "es" to 7,
            "Juggernaut" to 8,
            "juggernaut" to 8,
            "jugg" to 8,
            "jug" to 8,
            "Mirana" to 9,
            "mirana" to 9,
            "Morphling" to 10,
            "morph" to 10,
            "morphling" to 10,
            "Shadow Fiend" to 11,
            "sf" to 11,
            "shadowfiend" to 11,
            "Phantom Lancer" to 12,
            "pl" to 12,
            "phantomlancer" to 12,
            "Puck" to 13,
            "puck" to 13,
            "Pudge" to 14,
            "pudge" to 14,
            "Razor" to 15,
            "razor" to 15,
            "sandking" to 16,
            "Sand King" to 16,
            "sk" to 16,
            "Storm Spirit" to 17,
            "storm" to 17,
            "stormspirit" to 17,
            "Sven" to 18,
            "sven" to 18,
            "Tiny" to 19,
            "tiny" to 19,
            "Vengeful Spirit" to 20,
            "venge" to 20,
            "vengefulspirit" to 20,
            "Wind Runner" to 21,
            "wind" to 21,
            "wr" to 21,
            "windrunner" to 21,
            "windranger" to 21,
            "Zeus" to 22,
            "zeus" to 22,
            "Kunkka" to 23,
            "kunkka" to 23,
            "Lina" to 25,
            "lina" to 25,
            "Lion" to 26,
            "lion" to 26,
            "Shadow Shaman" to 27,
            "shaman" to 27,
            "shadowshaman" to 27,
            "Slardar" to 28,
            "slardar" to 28,
            "Tidehunter" to 29,
            "tidehunter" to 29,
            "tide" to 29,
            "Witch Doctor" to 30,
            "wd" to 30,
            "witchdoctor" to 30,
            "Lich" to 31,
            "lich" to 31,
            "Riki" to 32,
            "riki" to 32,
            "Enigma" to 33,
            "enigma" to 33,
            "Tinker" to 34,
            "tinker" to 34,
            "Sniper" to 35,
            "sniper" to 35,
            "Necrophos" to 36,
            "necro" to 36,
            "necrophos" to 36,
            "necrolyte" to 36,
            "Warlock" to 37,
            "warlock" to 37,
            "Beast Master" to 38,
            "beastmaster" to 38,
            "beast" to 38,
            "Queen Of Pain" to 39,
            "queenofpain" to 39,
            "qop" to 39,
            "Venomancer" to 40,
            "venomancer" to 40,
            "veno" to 40,
            "Faceless Void" to 41,
            "facelessvoid" to 41,
            "void" to 41,
            "Wraith King" to 42,
            "wraithking" to 42,
            "wk" to 42,
            "skeletonking" to 42,
            "Death Prophet" to 43,
            "deathprophet" to 43,
            "dp" to 43,
            "krobelus" to 43,
            "krob" to 43,
            "Phantom Assasin" to 44,
            "phantomassasin" to 44,
            "pa" to 44,
            "Pugna" to 45,
            "pugna" to 45,
            "Templar Assasin" to 46,
            "templarassasin" to 46,
            "ta" to 46,
            "Viper" to 47,
            "viper" to 47,
            "Luna" to 48,
            "luna" to 48,
            "Dragon Knight" to 49,
            "dragonknight" to 49,
            "dk" to 49,
            "Dazzle" to 50,
            "dazzle" to 50,
            "Clockwerk" to 51,
            "clockwerk" to 51,
            "clock" to 51,
            "Leshrac" to 52,
            "leshrac" to 52,
            "lesh" to 52,
            "Nature's Prophet" to 53,
            "furion" to 53,
            "nature'sprophet" to 53,
            "Lifestealer" to 54,
            "lifestealer" to 54,
            "ls" to 54,
            "naix" to 54,
            "Dark Seer" to 55,
            "darkseer" to 55,
            "ds" to 55,
            "Clinkz" to 56,
            "clinkz" to 56,
            "Omniknight" to 57,
            "omni" to 57,
            "omniknight" to 57,
            "Enchantress" to 58,
            "enchantress" to 58,
            "Huskar" to 59,
            "huskar" to 59,
            "Night Stalker" to 60,
            "nightstalker" to 60,
            "ns" to 60,
            "balanar" to 60,
            "Broodmother" to 61,
            "broodmother" to 61,
            "brood" to 61,
            "Bounty Hunter" to 62,
            "bountyhunter" to 62,
            "bh" to 62,
            "bounty" to 62,
            "Weaver" to 63,
            "weaver" to 63,
            "Jakiro" to 64,
            "jakiro" to 64,
            "thd" to 64,
            "Batrider" to 65,
            "batrider" to 65,
            "bat" to 65,
            "Chen" to 66,
            "chen" to 66,
            "Spectre" to 67,
            "spectre" to 67,
            "Ancient Apparition" to 68,
            "ancientapparition" to 68,
            "aa" to 68,
            "Doom" to 69,
            "doombringer" to 69,
            "doom" to 69,
            "Ursa" to 70,
            "ursa" to 70,
            "fuzzywuzzy" to 70,
            "Spirit Breaker" to 71,
            "spiritbreaker" to 71,
            "bara" to 71,
            "Gyrocopter" to 72,
            "gyrocopter" to 72,
            "gyro" to 72,
            "Alchemist" to 73,
            "alch" to 73,
            "alchemist" to 73,
            "Invoker" to 74,
            "invoker" to 74,
            "invo" to 74,
            "Silencer" to 75,
            "silencer" to 75,
            "Outworld Destroyer" to 76,
            "outworlddestroyer" to 76,
            "outworlddevourer" to 76,
            "obsidiandestroyer" to 76,
            "od" to 76,
            "Lycan" to 77,
            "lycan" to 77,
            "Brewmaster" to 78,
            "brewmaster" to 78,
            "brew" to 78,
            "Shadow Demon" to 79,
            "shadowdemon" to 79,
            "sd" to 79,
            "Lone Druid" to 80,
            "lonedruid" to 80,
            "ld" to 80,
            "lone" to 80,
            "Chaos Knight" to 81,
            "chaosknight" to 81,
            "ck" to 81,
            "Meepo" to 82,
            "meepo" to 82,
            "Treant Protector" to 83,
            "treantprotector" to 83,
            "tree" to 83,
            "treant" to 83,
            "Ogre Magi" to 84,
            "ogremagi" to 84,
            "ogre" to 84,
            "Undying" to 85,
            "undying" to 85,
            "Rubick" to 86,
            "rubick" to 86,
            "Disruptor" to 87,
            "disruptor" to 87,
            "thrall" to 87,
            "Nyx Assassin" to 88,
            "nyxassassin" to 88,
            "nyx" to 88,
            "Naga Siren" to 89,
            "nagasiren" to 89,
            "naga" to 89,
            "Keeper Of The Light" to 90,
            "keeperofthelight" to 90,
            "kotl" to 90,
            "ezalor" to 90,
            "Io" to 91,
            "wisp" to 91,
            "io" to 91,
            "Visage" to 92,
            "visage" to 92,
            "Slark" to 93,
            "slark" to 93,
            "murlocnightcrawler" to 93,
            "Medusa" to 94,
            "medusa" to 94,
            "Troll Warlord" to 95,
            "trollwarlord" to 95,
            "troll" to 95,
            "jahrakal" to 95,
            "Centaur Warrunner" to 96,
            "centaurwarrunner" to 96,
            "cw" to 96,
            "centaur" to 96,
            "Magnus" to 97,
            "magnus" to 97,
            "magnataur" to 97,
            "Timbersaw" to 98,
            "timbersaw" to 98,
            "timber" to 98,
            "Bristleback" to 99,
            "bristleback" to 99,
            "bb" to 99,
            "bristle" to 99,
            "Tusk" to 100,
            "tusk" to 100,
            "tuskar" to 100,
            "Skywrath Mage" to 101,
            "skywrathmage" to 101,
            "sky" to 101,
            "skywrath" to 101,
            "Abaddon" to 102,
            "abaddon" to 102,
            "Elder Titan" to 103,
            "eldertitan" to 103,
            "et" to 103,
            "Legion Commander" to 104,
            "legioncommander" to 104,
            "legion" to 104,
            "lc" to 104,
            "Techies" to 105,
            "techies" to 105,
            "Ember Spirit" to 106,
            "emberspirit" to 106,
            "ember" to 106,
            "Earth Spirit" to 107,
            "earthspirit" to 107,
            "Underlord" to 108,
            "underlord" to 108,
            "abyssalunderlord" to 108,
            "Terrorblade" to 109,
            "terrorblade" to 109,
            "tb" to 109,
            "Phoenix" to 110,
            "phoenix" to 110,
            "Oracle" to 111,
            "oracle" to 111,
            "Winter Wyvern" to 112,
            "winterwyvern" to 112,
            "ww" to 112,
            "winter" to 112,
            "Arc Warden" to 113,
            "arcwarden" to 113,
            "arc" to 113,
            "aw" to 113,
            "Monkey King" to 114,
            "monkeyking" to 114,
            "mk" to 114,
            "Dark Willow" to 119,
            "darkwillow" to 119,
            "willow" to 119,
            "Pangolier" to 120,
            "pangolier" to 120,
            "pango" to 120,
            "Grimstroke" to 121,
            "grimstroke" to 121,
            "grim" to 121,
            "Hoodwink" to 123,
            "hoodwink" to 123,
            "hood" to 123,
            "Void Spirit" to 126,
            "voidspirit" to 126,
            "Snapfire" to 128,
            "snapfire" to 128,
            "snap" to 128,
            "Mars" to 129,
            "mars" to 129,
            "Dawnbreaker" to 135,
            "dawnbreaker" to 135,
            "dawn" to 135,
            "Marci" to 136,
            "marci" to 136,
            "Primal Beast" to 137,
            "primalbeast" to 137,
            "primal" to 137
        )
    }
}